### ISSUE TITLE
Add four decently complicated queries.

### ISSUE THREAD

**Issue by Yash-Keswani** [Yash-Keswani/Badafone#6]
## Query Addition

We need ten queries for the project. We have six right now. We need four more. Currently there is only one query related to updating the database, at least two more would be good. Add two of miscellaneous things, typically those covered in class that aren't here, like groupby aggregation with having clauses. If you're out of ideas, look up notes on `windowing` and `ranking` in the lecture notes.

If you have any idea, write out the description as a comment on this issue before committing the query. Add any queries after this to the markdown file `Submission_2.md`

**Comment by nin-ran-jan** [comment]
Completed 4 querries and sent them to @Yash-Keswani to use in backend development.
